GET http://127.0.0.1:5000/simpson
Accept: application/json
Content-Type: application/json

{
  "5": 10,
  "10": 20,
  "15": 20
}

###

GET http://127.0.0.1:5000/average
Accept: application/json
Content-Type: application/json

{
  "points": [1,2,3,4]
}